'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.4.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "Funcionalidad para autoguardar My.Settings"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(sender As Global.System.Object, e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("25, 135, 209")>  _
        Public Property AccentColor1() As Global.System.Drawing.Color
            Get
                Return CType(Me("AccentColor1"),Global.System.Drawing.Color)
            End Get
            Set
                Me("AccentColor1") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0, 122, 204")>  _
        Public Property AccentColor2() As Global.System.Drawing.Color
            Get
                Return CType(Me("AccentColor2"),Global.System.Drawing.Color)
            End Get
            Set
                Me("AccentColor2") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0, 109, 183")>  _
        Public Property AccentColor3() As Global.System.Drawing.Color
            Get
                Return CType(Me("AccentColor3"),Global.System.Drawing.Color)
            End Get
            Set
                Me("AccentColor3") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("ControlDarkDark")>  _
        Public Property ColorDarken() As Global.System.Drawing.Color
            Get
                Return CType(Me("ColorDarken"),Global.System.Drawing.Color)
            End Get
            Set
                Me("ColorDarken") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("ControlDark")>  _
        Public Property ColorDark() As Global.System.Drawing.Color
            Get
                Return CType(Me("ColorDark"),Global.System.Drawing.Color)
            End Get
            Set
                Me("ColorDark") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Control")>  _
        Public Property ColorLight() As Global.System.Drawing.Color
            Get
                Return CType(Me("ColorLight"),Global.System.Drawing.Color)
            End Get
            Set
                Me("ColorLight") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Black")>  _
        Public Property AbsoluteDark() As Global.System.Drawing.Color
            Get
                Return CType(Me("AbsoluteDark"),Global.System.Drawing.Color)
            End Get
            Set
                Me("AbsoluteDark") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("250, 250, 250")>  _
        Public Property AbsoluteLight() As Global.System.Drawing.Color
            Get
                Return CType(Me("AbsoluteLight"),Global.System.Drawing.Color)
            End Get
            Set
                Me("AbsoluteLight") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property RoundedButtons() As Boolean
            Get
                Return CType(Me("RoundedButtons"),Boolean)
            End Get
            Set
                Me("RoundedButtons") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("100")>  _
        Public Property RoundedResolution() As Integer
            Get
                Return CType(Me("RoundedResolution"),Integer)
            End Get
            Set
                Me("RoundedResolution") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("White")>  _
        Public Property AccentForeColor() As Global.System.Drawing.Color
            Get
                Return CType(Me("AccentForeColor"),Global.System.Drawing.Color)
            End Get
            Set
                Me("AccentForeColor") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Control")>  _
        Public Property Color() As Global.System.Drawing.Color
            Get
                Return CType(Me("Color"),Global.System.Drawing.Color)
            End Get
            Set
                Me("Color") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Window")>  _
        Public Property ColorLighten() As Global.System.Drawing.Color
            Get
                Return CType(Me("ColorLighten"),Global.System.Drawing.Color)
            End Get
            Set
                Me("ColorLighten") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("09:00:00")>  _
        Public Property StartTime() As Global.System.TimeSpan
            Get
                Return CType(Me("StartTime"),Global.System.TimeSpan)
            End Get
            Set
                Me("StartTime") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("18:00:00")>  _
        Public Property EndTime() As Global.System.TimeSpan
            Get
                Return CType(Me("EndTime"),Global.System.TimeSpan)
            End Get
            Set
                Me("EndTime") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("00:05:00")>  _
        Public Property IntervalTime() As Global.System.TimeSpan
            Get
                Return CType(Me("IntervalTime"),Global.System.TimeSpan)
            End Get
            Set
                Me("IntervalTime") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property IntervalAction() As Byte
            Get
                Return CType(Me("IntervalAction"),Byte)
            End Get
            Set
                Me("IntervalAction") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property NotifyTitle() As String
            Get
                Return CType(Me("NotifyTitle"),String)
            End Get
            Set
                Me("NotifyTitle") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property NotifyText() As String
            Get
                Return CType(Me("NotifyText"),String)
            End Get
            Set
                Me("NotifyText") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("00:00:05")>  _
        Public Property NotifyDuration() As Global.System.TimeSpan
            Get
                Return CType(Me("NotifyDuration"),Global.System.TimeSpan)
            End Get
            Set
                Me("NotifyDuration") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property NotifyAtenuarPantalla() As Boolean
            Get
                Return CType(Me("NotifyAtenuarPantalla"),Boolean)
            End Get
            Set
                Me("NotifyAtenuarPantalla") = value
            End Set
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.TimeReminder.My.MySettings
            Get
                Return Global.TimeReminder.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
